BrotherPairing/urls.py
from django.contrib import admin
from django.urls import path, include
from django.shortcuts import redirect

urlpatterns = [
    path('', lambda request: redirect('pairing/', permanent=False)),
    path('pairing/', include('pairing.urls')),
    path('admin/', admin.site.urls),
]

pairing/urls.py
from django.contrib import admin
from django.urls import path, include
from django.shortcuts import redirect
from . import views

app_name = 'pairing'

urlpatterns = [
    path('', views.index, name='index'),
    path('show_pairings/', views.show_pairings, name='show_pairings'),
]

pairing/models.py
from django.db import models

# Create your models here.
class Brother(models.Model):
    first_name = models.CharField(max_length=30)
    last_name = models.CharField(max_length=30)
    phone_number = models.CharField(max_length=15)
    new_members = models.ManyToManyField('Pledge', related_name='pledge')

    def __str__(self) -> str:
        return self.first_name + " " + self.last_name
    
class Pledge(models.Model):
    first_name = models.CharField(max_length=30)
    last_name = models.CharField(max_length=30)
    phone_number = models.CharField(max_length=15)
    brothers = models.ManyToManyField('Brother', related_name='brother')

    def __str__(self) -> str:
        return self.first_name + " " + self.last_name
    
class Pairing(models.Model):
    week_start = models.DateField()
    week_end = models.DateField()
    brother = models.ForeignKey('Brother', on_delete=models.CASCADE, related_name='pairings')
    pledge = models.ForeignKey('Pledge', on_delete=models.CASCADE)

    def __str__(self):
        return self.brother.first_name + " " + self.brother.last_name + " - " + self.pledge.first_name + " " + self.pledge.last_name

pairing/views.py
from django.shortcuts import render

import pandas as pd
from random import choice
from django.shortcuts import render
from datetime import date, timedelta

from .models import Brother, Pledge, Pairing
# Create your views here.

def index(request):
    return render(request, 'pairing/index.html')

def read_excel_file(file_path):
    """Reads an Excel file and returns the data as a list of dictionaries."""
    data = []
    df = pd.read_excel(file_path, header=None)
    for row in df.values:
        first_name = row[0]
        last_name = row[1]
        phone_number = row[2]
        data.append({'first_name': first_name, 'last_name': last_name, 'phone_number': phone_number})
    return data

def show_pairings(request):
    week_start = date.today() - timedelta(days=date.today().weekday())
    pairings = Pairing.objects.filter(week_start=week_start)
    if len(pairings) == 0:
        generate_pairings(request=request)
    pairings = Pairing.objects.filter(week_start=week_start)
    context = {'pairings': pairings}
    return render(request, 'pairing/pairings.html', context)

def generate_pairings(request):
    # Read brothers and pledges data from Excel sheets
    brothers_data = read_excel_file('brothers.xlsx')
    pledges_data = read_excel_file('pledges.xlsx')
    # Create brothers and pledges if they don't exist already
    brothers = []
    for row in brothers_data:
        brother,created = Brother.objects.get_or_create(
            first_name=row['first_name'],
            last_name=row['last_name'],
            phone_number =row['phone_number']
        )
        brothers.append(brother)

    pledges = []
    for row in pledges_data:
        pledge,created = Pledge.objects.get_or_create(
            first_name=row['first_name'],
            last_name=row['last_name'],
            phone_number =row['phone_number']
        )
        pledges.append(pledge)

    # Get the current week's pairings
    week_start = date.today() - timedelta(days=date.today().weekday())
    week_end = week_start + timedelta(days=5)
    # so it resets a day early
    # available_brothers = {}
    # for pledge in pledges:
    #     available_brothers[pledge] = brothers
    
    # Pair pledges with brothers
    # current_pairings = Pairing.objects.filter(week_start=week_start, week_end=week_end)

    # Pair pledges with brothers
    print("There are",len(brothers),"Brothers")
    i = 1
    for brother in brothers:
        print(i, brother)
        i += 1
    pairings = []
    available_brothers = {}
    for pledge in pledges:
        # Get brothers that are available for this pledge
        paired_brothers = Pairing.objects.filter(pledge=pledge).values_list('brother', flat=True)
        print("# of Paired Bros",(len(paired_brothers)))
        other_paired_brothers = Pairing.objects.filter(week_start=week_start, week_end=week_end).exclude(pledge=pledge).values_list('brother', flat=True)
        print("# of Other Paired Bros",(len(other_paired_brothers)))
        available_brothers[pledge] = Brother.objects.exclude(id__in=paired_brothers).exclude(id__in=other_paired_brothers)
        
        # Pair the pledge with an available brother
        if available_brothers[pledge]:
            brother = choice(available_brothers[pledge])
            pairing = Pairing(
                pledge=pledge,
                brother=brother,
                week_start=week_start,
                week_end=week_end
            )
            pairing.save()
            print(len(available_brothers[pledge]))
            pairings.append(pairing)
    
    

pairing/templates/pairing/index.html
<!DOCTYPE html>
<html lang="en">
{% load static %}

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>BrotherPairing</title>
    <link rel="stylesheet" href="{% static 'pairing/style.css' %}">
</head>

<body>
    <div class="button-container">
        <img src="../../static/pairing/ThetaTau.png" alt="">
        <h1>Welcome to the Pairings App</h1>
        <p>Click the button below to generate new pairings:</p>
        <a href="{% url 'pairing:show_pairings' %}" class="btn btn-primary">Generate Pairings</a>
    </div>

</body>

</html>

pairing/templates/pairing/pairings.html
<!DOCTYPE html>
<html lang="en">
{% load static %}

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>BrotherPairing</title>
    <link rel="stylesheet" href="{% static 'pairing/pairing_style.css' %}">
</head>

<body>
    {% if pairings %}
    <h2>Current Pairings</h2>
    <table>
        <thead>
            <tr>
                <th>Phone Number</th>
                <th>Pledge</th>
                <th>Brother</th>
                <th>Phone Number</th>
            </tr>
        </thead>
        <tbody>
            {% for pairing in pairings %}
            <tr>
                <td>{{ pairing.pledge.phone_number }}</td>
                <td>{{ pairing.pledge.first_name }} {{ pairing.pledge.last_name }}</td>
                <td>{{ pairing.brother.first_name }} {{ pairing.brother.last_name }}</td>
                <td>{{ pairing.brother.phone_number }}</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
    {% else %}
    <p>No pairings found for the current week.</p>
    {% endif %}
</body>

</html>